import React from "react";
import "./Projects.css";
import ProjectCard from "./ProjectCard";

function Cards() {
  return (
    <div className="cards">
      <h1>Projects</h1>
      <div className="cards__container">
        <div className="cards__wrapper">
          <ul className="cards__items">
            <ProjectCard
              src="images/aboutImg.png"
              text="Uses a Generative Adversarial Network to generate images of anime backgrounds. (This is an image generated by the AI btw)"
              title="Ganime"
              link="https://github.com/cjyu81/Project-GANime"
            />
            <ProjectCard
              src="images/anya.png"
              text="Enables collaboration through realtime drawing. (pls dont judge my drawing, I was using a mouse) "
              title="Brainstormy"
              link="https://github.com/anthien30/brainstormy"
            />
          </ul>
        </div>
      </div>
    </div>
  );
}

export default Cards;
